#pragma once

#include <cstdint>

#include "../LevelEdit/resource.h"

namespace leveledit_qt {

// MFC shared command IDs that are not defined in LevelEdit's resource.h.
constexpr int kIdFileNew = 0xE100;
constexpr int kIdFileOpen = 0xE101;
constexpr int kIdFileSave = 0xE103;
constexpr int kIdFileSaveAs = 0xE104;
constexpr int kIdAppExit = 0xE141;
constexpr int kIdEditUndo = 0xE12B;
constexpr int kIdEditCut = 0xE123;
constexpr int kIdEditCopy = 0xE122;
constexpr int kIdEditPaste = 0xE125;
constexpr int kIdViewToolbar = 0xE800;
constexpr int kIdViewStatusBar = 0xE801;

enum class CommandId : int32_t {
    FileNew = kIdFileNew,
    FileOpen = kIdFileOpen,
    FileSave = kIdFileSave,
    FileSaveAs = kIdFileSaveAs,
    FileExit = kIdAppExit,

    EditUndo = kIdEditUndo,
    EditCut = kIdEditCut,
    EditCopy = kIdEditCopy,
    EditPaste = kIdEditPaste,

    ViewToolbar = kIdViewToolbar,
    ViewStatusBar = kIdViewStatusBar,

    SavePresets = IDM_SAVE_PRESETS,
    LevelExport = IDM_LEVEL_EXPORT,
    AlwaysExport = IDM_ALWAYS_EXPORT,
    AlwaysLocalExport = IDM_ALWAYS_LOCAL_EXPORT,
    BatchExport = IDM_BATCH_EXPORT,
    ExportLanguage = IDM_EXPORT_LANGUAGE,
    ExportInstallerLanguageVersion = IDM_EXPORT_INSTALLER_LANGUAGE_VERSION,
    ModExport = IDM_MOD_EXPORT,
    SpecifyAssetDatabase = IDM_SPECIFY_ASSET_DATABASE,
    ChangeBase = IDM_CHANGE_BASE,
    EditIncludes = IDM_EDIT_INCLUDES,
    Repartition = IDM_REPARTITION,
    VerifyCulling = IDM_VERIFY_CULLING,
    ToggleTerrainSelection = IDM_TOGGLE_TERRAIN_SELECTION,
    ModeCamera = IDM_MODE_CAMERA,
    ObjectManipulate = IDM_OBJECT_MANIPULATE,
    ModeOrbit = IDM_MODE_ORBIT,
    ModeWalkthrough = IDM_MODE_WALKTHROUGH,
    ToggleWireframeMode = IDM_TOGGLE_WIREFRAME_MODE,
    BackgroundSettings = IDM_BACKGROUND_SETTINGS,
    EditLevelSettings = IDM_EDIT_LEVEL_SETTINGS,
    ViewFullscreen = IDM_VIEW_FULLSCREEN,
    ViewChangeDevice = IDM_VIEW_CHANGE_DEVICE,
    VisualOptions = IDM_VISUAL_OPTIONS,
    DisplayStaticAnimObjects = IDM_DISPLAY_STATIC_ANIM_OBJECTS,
    ShowEditorObjects = IDM_SHOW_EDITOR_OBJECTS,
    ViewSoundSpheres = IDM_VIEW_SOUND_SPHERES,
    ViewLightSpheres = IDM_VIEW_LIGHT_SPHERES,
    ToggleAttenuationSpheres = IDM_TOGGLE_ATTENUATION_SPHERES,
    BuildingPowerOn = IDM_BUILDING_POWER_ON,
    DropToGround = IDM_DROP_TO_GROUND,
    LockObjects = IDM_LOCK_OBJECTS,
    UnlockObjects = IDM_UNLOCK_OBJECTS,
    IncreaseSphere = IDM_INCREASE_SPHERE,
    DecreaseSphere = IDM_DECREASE_SPHERE,
    ImportDynObjs = IDM_IMPORT_DYN_OBJS,
    ExportDynObjs = IDM_EXPORT_DYN_OBJS,
    ImportStatic = IDM_IMPORT_STATIC,
    ExportStatic = IDM_EXPORT_STATIC,
    ExportTileList = IDM_EXPORT_TILE_LIST,
    BulkReplace = IDM_BULK_REPLACE,
    AddChildNode = IDM_ADD_CHILD_NODE,
    GotoObject = IDM_GOTO_OBJECT,
    SetNodeIdStart = IDM_SET_NODE_ID_START,
    CheckIds = IDM_CHECK_IDS,
    FixIdCollisions = IDM_FIX_ID_COLLISIONS,
    RemapUnimportantIds = IDM_REMAP_UNIMPORTANT_IDS,
    RemapIds = IDM_REMAP_IDS,
    UseVisCamera = IDM_USE_VIS_CAMERA,
    EnableVisSectorFallback = IDM_ENABLE_VIS_SECTOR_FALLBACK,
    ViewVisErrors = IDM_VIEW_VIS_ERRORS,
    VisStats = IDM_VIS_STATS,
    ViewVisPoints = IDM_VIEW_VIS_POINTS,
    ViewVisWindow = IDM_VIEW_VIS_WINDOW,
    ToggleManVisPoints = IDM_TOGGLE_MAN_VIS_POINTS,
    MakeVisPoint = IDM_MAKE_VIS_POINT,
    DiscardVis = IDM_DISCARD_VIS,
    ResetDynaCullSystem = IDM_RESET_DYNA_CULL_SYSTEM,
    ImportVis = IDM_IMPORT_VIS,
    RunJob = IDM_RUN_JOB,
    ImportVisRemapData = IDM_IMPORT_VIS_REMAP_DATA,
    ExportVisRemapData = IDM_EXPORT_VIS_REMAP_DATA,
    RunManualVisPoints = IDM_RUN_MANUAL_VIS_POINTS,
    BuildDynaCullsys = IDM_BUILD_DYNA_CULLSYS,
    AutoGenVis = IDM_AUTO_GEN_VIS,
    OptimizeVisData = IDM_OPTIMIZE_VIS_DATA,
    GenerateObstacleVolumes = IDM_GENERATE_OBSTACLE_VOLUMES,
    BuildFlightInfo = IDM_BUILD_FLIGHT_INFO,
    DisplayPathfindSectors = IDM_DISPLAY_PATHFIND_SECTORS,
    DisplayPathfindPortals = IDM_DISPLAY_PATHFIND_PORTALS,
    DisplayPaths = IDM_DISPLAY_PATHS,
    DisplayFullPaths = IDM_DISPLAY_FULL_PATHS,
    TestPathfind = IDM_TEST_PATHFIND,
    TestGoto = IDM_TEST_GOTO,
    DisplayPathfindRawData = IDM_DISPLAY_PATHFIND_RAW_DATA,
    DisplayWeb = IDM_DISPLAY_WEB,
    DiscardPathfind = IDM_DISCARD_PATHFIND,
    ImportPathfind = IDM_IMPORT_PATHFIND,
    ExportPathfind = IDM_EXPORT_PATHFIND,
    ToggleLights = IDM_TOGGLE_LIGHTS,
    DisplayLightVectors = IDM_DISPLAY_LIGHT_VECTORS,
    ToggleSunlight = IDM_TOGGLE_SUNLIGHT,
    EditSunlight = IDM_EDIT_SUNLIGHT,
    ViewAmbientLightDlg = IDM_VIEW_AMBIENT_LIGHT_DLG,
    PrelitVertex = IDM_PRELIT_VERTEX,
    PrelitMultipass = IDM_PRELIT_MULTIPASS,
    PrelitMultitex = IDM_PRELIT_MULTITEX,
    ImportLights = IDM_IMPORT_LIGHTS,
    ImportSunlight = IDM_IMPORT_SUNLIGHT,
    ExportLights = IDM_EXPORT_LIGHTS,
    ComputeVertexSolve = IDM_COMPUTE_VERTEX_SOLVE,
    ToggleMusic = IDM_TOGGLE_MUSIC,
    ToggleSounds = IDM_TOGGLE_SOUNDS,
    CameraTop = IDM_CAMERA_TOP,
    CameraBottom = IDM_CAMERA_BOTTOM,
    CameraFront = IDM_CAMERA_FRONT,
    CameraBack = IDM_CAMERA_BACK,
    CameraLeft = IDM_CAMERA_LEFT,
    CameraRight = IDM_CAMERA_RIGHT,
    CameraPerspective = IDM_CAMERA_PERSPECTIVE,
    CameraOrthographic = IDM_CAMERA_ORTHOGRAPHIC,
    AutoLevel = IDM_AUTOLEVEL,
    CameraDepthLess = IDM_CAMERA_DEPTH_LESS,
    CameraDepthMore = IDM_CAMERA_DEPTH_MORE,
    GotoLocation = IDM_GOTO_LOCATION,
    ImportStringIds = IDM_IMPORT_STRING_IDS,
    ExportStringIds = IDM_EXPORT_STRING_IDS,
    EditStringsTable = IDM_EDIT_STRINGS_TABLE,
    ExportTranslationData = IDM_EXPORT_TRANSLATION_DATA,
    ImportTranslationData = IDM_IMPORT_TRANSLATION_DATA,
    ImmediatePresetCheckIn = IDM_IMMEDIATE_PRESET_CHECKIN,
    CheckInPresetChanges = IDM_CHECK_IN_PRESET_CHANGES,
    ExportPresets = IDM_EXPORT_PRESETS,
    ImportPresets = IDM_IMPORT_PRESETS,
    ExportPresetFileDependencies = IDM_EXPORT_PRESET_FILE_DEPENDENCIES,
    ExportFileUsageReport = IDM_EXPORT_FILE_USAGE_REPORT,
    ExportMissingTranslationReport = IDM_EXPORT_MISSING_TRANSLATION_REPORT,
    DebugScriptsMode = IDM_DEBUG_SCRIPTS_MODE,
    CreateProxies = IDM_CREATE_PROXIES,
    CheckMemLog = IDM_CHECK_MEMLOG,
    ExtractRcStrings = IDM_EXTRACT_RC_STRINGS,
    ExtractInstallerRcStrings = IDM_EXTRACT_INSTALLER_RC_STRINGS,
    ImportSounds = IDM_IMPORT_SOUNDS,

    RotateLeft = IDM_ROTATE_LEFT,
    RotateRight = IDM_ROTATE_RIGHT,
    VolDec = IDM_VOL_DEC,
    VolInc = IDM_VOL_INC,
    CamSpeedIncrease = IDM_CAM_SPEED_INCREASE,
    CamSpeedDecrease = IDM_CAM_SPEED_DECREASE,
    DeleteSelection = IDM_DELETE_SELECTION,
    Escape = IDM_ESCAPE,
    VisInvert = IDM_VIS_INVERT,
    VisDisable = IDM_VIS_DISABLE,
    TogglePerformanceSampling = IDM_TOGGLE_PERFORMANCE_SAMPLING,
    CamElevateDn = IDM_CAM_ELEVATE_DN,
    CamBkwd = IDM_CAM_BKWD,
    CamLookDn = IDM_CAM_LOOK_DN,
    CamTurnLeft = IDM_CAM_TURN_LEFT,
    CamReset = IDM_CAM_RESET,
    CamTurnRight = IDM_CAM_TURN_RIGHT,
    CamElevateUp = IDM_CAM_ELEVATE_UP,
    CamFwd = IDM_CAM_FWD,
    CamLookUp = IDM_CAM_LOOK_UP,
    GenVis = IDM_GEN_VIS,
    RestrictX = IDM_RESTRICT_X,
    RestrictY = IDM_RESTRICT_Y,
    RestrictZ = IDM_RESTRICT_Z,
};

inline constexpr int LegacyCommandValue(CommandId id)
{
    return static_cast<int>(id);
}

} // namespace leveledit_qt
